apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: apache-service
  name: apache-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: apache-service
  type: NodePort
status:
  loadBalancer: {}
