apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: product-frontend-service
    visualize: "true"
  name: product-frontend-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: product-frontend-deployment
  type: NodePort
status:
  loadBalancer: {}

