apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: product-stock-service
  name: product-stock-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: product-stock-deployment
  type: NodePort
status:
  loadBalancer: {}

