spring:
  application:
    name: product-orch-svc
  main:
    banner-mode: "off"

server:
  port: 8080
  servlet:
    context-path: /product-orch-svc
    
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["configprops", "env","metrics", "promatheus", "health", "info", "threaddump"]
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
    web:
      server:
        auto-time-requests: false
    distribution:
      percentiles:
        all: 0.5, 0.7
  prometheus:
    enabled: true
  server:
    port: ${server.port}

services:
  stock:
    connectionTimeout: 4000
    readTimeout: 6000
    http-headers:
      "[Content-Type]": application/json
    base-path: /product-stock-svc
    path: /stocks
  pd:
    connectionTimeout: 4000
    readTimeout: 6000
    http-headers:
      "[Content-Type]": application/json
    base-path: /product-detail-svc
    path: /products
    
---
spring:
  profiles: k8s
  
services:
  stock:
    schema: ${STOCK_API_SCHEMA}
    host: ${STOCK_API_HOST}
    port: ${STOCK_API_PORT}
  pd:
    schema: ${PRODUCT_API_SCHEMA}
    host: ${PRODUCT_API_HOST}
    port: ${PRODUCT_API_PORT}
    
---
spring:
  profiles: local
  
server:
  port: 8083

services:
  stock:
    schema: http
    host: localhost
    port: 8082
  pd:
    schema: http
    host: localhost
    port: 8081
    