apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-detail-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-detail-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
