apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-frontend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-frontend-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
