apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache-deployment
    version: "1.0"
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache-deployment
    spec:
      containers:
      - name: apache-deployment
        image: gcr.io/tonal-carving-252503/products-istio-apache:latest
        ports:
        - containerPort: 80
        resources: {}
status: {}
