apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: product-stock-deployment
    version: "1.0"
  name: product-stock-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-stock-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-stock-deployment
    spec:
      containers:
      - name: product-stock-deployment
        # image: souvikmukherjeedocker/shopping-app_product-stock-svc:v1
        image: gcr.io/tonal-carving-252503/product-stock-svc:v2
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
status: {}
