apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: product-detail-deployment
    version: "1.0"
  name: product-detail-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-detail-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-detail-deployment
    spec:
      containers:
      - name: product-detail-deployment
        image: souvikmukherjeedocker/shopping-app_product-detail-svc:v1
        ports:
        - containerPort: 8080
        resources: {}
status: {}

