apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: product-frontend-deployment
    version: "1.0"
  name: product-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-frontend-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-frontend-deployment
    spec:
      containers:
      - name: product-frontend-deployment
        # image: souvikmukherjeedocker/shopping-app_product-frontend-svc:v1
        image: gcr.io/tonal-carving-252503/product-frontend-svc:v2
        ports:
        - containerPort: 8080
        resources: 
          requests: 
            cpu: 200m
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: PRODUCT_ORCH_SCHEMA
          value: http
        - name: PRODUCT_ORCH_HOST
          value: product-orch-service.default.svc.cluster.local
        - name: PRODUCT_ORCH_PORT
          value: '8080'
status: {}
