apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-stock-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: product-stock-deploy
    spec:
      containers:
      - name: product-stock-deploy
        # image: docker.pkg.github.com/mukherjeesouvik/shopping-app/product-stock-svc:v1
        image: souvikmukherjeedocker/shopping-app_product-stock-svc:v1
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /liveness
        #     port: 8080
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 8080
        #   initialDelaySeconds: 15
        #   timeoutSeconds: 30
