management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["configprops", "env","metrics", "promatheus", "health", "info", "threaddump"]
  metrics:
    enabled: false
    export:
      prometheus:
        enabled: true
    web:
      server:
        auto-time-requests: false
    distribution:
      percentiles:
        all: 0.5, 0.7
  prometheus:
    enabled: true
  server:
    port: 8080
spring:
  application:
    name: product-frontend-svc
  main:
    banner-mode: "off"

server:
  port: 8080
  servlet:
    context-path: /product-frontend-svc

services:
  productorch:
    schema: http
    host: localhost
    port: 8080
    connectionTimeout: 4000
    readTimeout: 6000
    http-headers:
      "[Content-Type]": application/json
    base-path: /product-orch-svc
    path: /products
    
---
spring:
  profiles: cluster-ip-configuration
  
services:
  productorch:
    schema: ${PRODUCT_ORCH_SCHEMA}
    host: ${PRODUCT_ORCH_HOST}
    port: ${PRODUCT_ORCH_PORT}
    

