apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: product-orch-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - apache-gateway
  http:
  - match:
    - uri:
        prefix: /products
#    rewrite:
#      uri: /
    route:
    - destination:
        port:
          number: 8080
        host: product-orch-service.default.svc.cluster.local
