apiVersion: v1
kind: Service
metadata:
  name: product-stock-service
  labels:
    name: product-stock-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: product-stock-deployment
  type: ClusterIP
